services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=root
      - REDIS_PORT=6379
    ports:
      - "6379:6379"

  db:
    container_name: globalpostgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tosuki_auth
    ports:
      - "5432:5432"